apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-app
  template:
    metadata:
      labels:
        app: kubernetes-app
    spec:
      containers:
      - name: myapp-container
        image: myapp-multi:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
